using IsaB.Entities;
using System.Collections.Generic;

namespace IsaB.QueryStack
{
    public class DatabaseService : IDatabaseService
    {
        public DatabaseService(string dbPath)
        {
            DatabasePath = dbPath;
        }
        #region Props
        public string DatabasePath { get; private set; }
        #endregion
        public void InitializeDataSource()
        {
            CheckDbAndSeed(DatabasePath);
        }
        #region Private Methods
        private List<string> GetSeedStringFromList()
        {
            List<string> builder2 = new List<string>() {
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(1, 1, 'Holzfachwerk, Ziegelmauerwerk', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(2, 1, 'Fugenglattstrich, Putz, Verkleidung mit Faserzementplatten, Bitumenschindeln oder einfachen Kunststoffplatten', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(3, 1, 'kein oder deutlich nicht zeitgemäßer Wärmeschutz (vor ca. 1980)', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(4, 2, 'ein-/zweischaliges Mauerwerk, z. B. Gitterziegel oder Hohlblocksteine', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(5, 2, 'verputzt und gestrichen oder Holzverkleidung', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(6, 2, 'nicht zeitgemäßer Wärmeschutz (vor ca. 1995)', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(7, 3, 'ein-/zweischaliges Mauerwerk, z. B. aus Leichtziegeln, Kalksandsteinen, Gasbetonsteinen', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(8, 3, 'Edelputz', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(9, 3, 'Wärmedämmverbundsystem oder Wärmedämmputz (nach ca. 1995)', 1, 1);",
            @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(10, 4, 'Verblendmauerwerk, zweischalig, hinterlüftet, Vorhangfassade (z. B. Naturschiefer)', 1, 1);",
             @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(11, 4, 'Wärmedämmung (nach ca. 2005)', 1, 1);",
               @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(12, 5, 'aufwendig gestaltete Fassaden mit konstruktiver Gliederung (Säulenstellungen, Erker etc.), Sichtbeton-Fertigteile, Natursteinfassade, Elemente aus Kupfer-/Eloxalblech, mehrgeschossige Glasfassaden', 1, 1);",
               @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(13, 5, 'Dämmung im Passivhausstandard', 1, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(14, 1, 'Dachpappe, Faserzementplatten/Wellplatten', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(15, 1, 'keine bis geringe Dachdämmung', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(16, 2, 'einfache Betondachsteine oder Tondachziegel, Bitumenschindeln', 2, 1);",
                 @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(17, 2, 'nicht zeitgemäße Dachdämmung (vor ca. 1995)', 2, 1);",
               @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(18, 3, 'Faserzement-Schindeln, beschichtete Betondachsteine und Tondachziegel, Folienabdichtung', 2, 1);",
               @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(19, 3, 'Rinnen und Fallrohre aus Zinkblech', 2, 1);",
               @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(20, 3, 'Dachdämmung (nach ca. 1995)', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(21, 4, 'glasierte Tondachziegel, Flachdachausbildung tlw. als Dachterrassen', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(22, 4, 'Konstruktion in Brettschichtholz, schweres Massivflachdach', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(23, 4, 'besondere Dachformen, z. B. Mansarden-, Walmdach', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(24, 4, 'Aufsparrendämmung, überdurchschnittliche Dämmung (nach ca. 2005)', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(25, 5, 'hochwertige Eindeckung z. B. aus Schiefer oder Kupfer, Dachbegrünung, befahrbares Flachdach', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(26, 5, 'aufwendig gegliederte Dachlandschaft, sichtbare Bogendachkonstruktionen', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(27, 5, 'Rinnen und Fallrohre aus  Kupfer', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(28, 5, 'Dämmung im Passivhausstandard', 2, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(29, 1, 'Einfachverglasung', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(30, 1, 'einfache Holztüren', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(31, 2, 'Zweifachverglasung (vor ca. 1995)', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(32, 2, 'Haustür mit nicht zeitgemäßem Wärmeschutz (vor ca. 1995)', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(33, 3, 'Zweifachverglasung (nach ca. 1995), Rollläden (manuell)', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(34, 3, 'Haus tür mit zeitgemäßem Wärmeschutz (nach ca. 1995)', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(35, 4, 'Dreifachverglasung, Sonnenschutzglas, aufwendigere Rahmen, Rollläden (elektr.)', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(36, 4, 'höherwertige Türanlage z. B. mit Seitenteil, besonderer Einbruchschutz', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(37, 5, 'große feststehende Fensterflächen, Spezialverglasung (Schall- und Sonnenschutz)', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(38, 5, 'Außentüren in hochwertigen Materialien', 3, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(39, 1, 'Fachwerkwände, einfache Putze/Lehmputze, einfache Kalkanstriche', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(40, 1, 'Füllungstüren, gestrichen, mit einfachen Beschlägen ohne Dichtungen', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(41, 2, 'massive tragende Innenwände, nicht tragende Wände in Leichtbauweise (z. B. Holzständerwände mit Gipskarton), Gipsdielen', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(42, 2, 'leichte Türen, Stahlzargen', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(43, 3, 'nicht tragende Innenwände in massiver Ausführung bzw. mit Dämmmaterial gefüllte Ständerkonstruktionen', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(44, 3, 'schwere Türen, Holzzargen', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(45, 4, 'Sichtmauerwerk, Wandvertäfelungen  (Holzpaneele)', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(46, 4, 'Massivholztüren, Schiebetürelemente, Glastüren, strukturierte Türblätter', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(47, 5, 'gestaltete Wandabläufe (z. B. Pfeilervorlagen, abgesetzte oder geschwungene Wandpartien)', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(48, 5, 'Vertäfelungen (Edelholz, Metall), Akustikputz, Brandschutzverkleidung', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(49, 5, 'raumhohe aufwendige Türelemente', 4, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(50, 1, 'Holzbalkendecken ohne Füllung, Spalierputz', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(51, 1, 'Weichholztreppen in einfacher Art und Ausführung', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(52, 1, 'kein Trittschallschutz', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(53, 2, 'Holzbalkendecken mit Füllung, Kappendecken', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(54, 2, 'Stahloder Hartholztreppen in einfacher Art und Ausführung', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(55, 3, 'Beton- und Holzbalkendecken mit Tritt- und Luftschallschutz (z. B. schwimmender Estrich)', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(56, 3, 'geradläufige Treppen aus Stahlbeton oder Stahl, Harfentreppe, Trittschallschutz', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(57, 4, 'Decken mit größerer Spannweite, Deckenverkleidung (Holzpaneele/Kassetten)', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(58, 4, 'gewendelte Treppen aus Stahlbeton oder Stahl, Hartholztreppenanlage in besserer Art und Ausführung', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(59, 5, 'Decken mit großen Spannweiten, gegliedert, Deckenvertäfelungen  (Edelholz, Metall)', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(60, 5, 'breite Stahlbeton-, Metall- oder Hartholztreppenanlage  mit hochwertigem  Geländer', 5, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(61, 1, 'ohne Belag', 6, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(62, 2, 'Linoleum-, Teppich-, Laminat- und PVC-Böden einfacher Art und Ausführung', 6, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(63, 3, 'Linoleum-, Teppich-, Laminat- und PVC-Böden besserer Art und Ausführung, Fliesen, Kunststeinplatten', 6, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(64, 4, 'Natursteinplatten, Fertigparkett, hochwertige Fliesen, Terrazzobelag, hochwertige Massivholzböden auf gedämmter Unterkonstruktion', 6, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(65, 5, 'hochwertiges Parkett, hochwertige Natursteinplatten, hochwertige Edelholzböden auf gedämmter Unterkonstruktion', 6, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(66, 1, 'einfaches Bad mit Stand-WC, Installation auf Putz, Ölfarbenanstrich, einfache PVC-Bodenbeläge', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(67, 2, '1 Bad mit WC, Dusche oder Badewanne', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(68, 2, 'einfache Wand- und Bodenfliesen, teilweise gefliest', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(69, 3, '1 Bad mit WC, Dusche und Badewanne, Gäste-WC', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(70, 3, 'Wand- und Bodenfliesen, raumhoch gefliest', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(71, 4, '1 – 2 Bäder mit tlw. zwei Waschbecken, tlw. Bidet/Urinal, Gäste-WC, bodengleiche Dusche', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(72, 4, 'Wand- und Bodenfliesen; jeweils in gehobener Qualität', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(73, 5, 'mehrere großzügige, hochwertige Bäder, Gäste-WC;', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(74, 5, 'hochwertige Wand- und Bodenplatten (oberflächenstrukturiert, Einzel- und Flächendekors)', 7, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(75, 1, 'Einzelöfen, Schwerkraftheizung', 8, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(76, 2, 'Fern- oder Zentralheizung, einfache Warmluftheizung, einzelne Gasaußenwandthermen, Nachtstromspeicher-, Fußbodenheizung (vor ca. 1995)', 8, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(77, 3, 'elektronisch gesteuerte Fern- oder Zentralheizung, Niedertemperatur- oder Brennwertkessel', 8, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(78, 4, 'Fußbodenheizung, Solarkollektoren für Warmwassererzeugung, zusätzlicher  Kaminanschluss', 8, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(79, 5, 'Solarkollektoren für Warmwassererzeugung und Heizung, Blockheizkraftwerk, Wärmepumpe, Hybrid-Systeme', 8, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(80, 5, 'aufwendige zusätzliche Kaminanlage', 8, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(81, 1, 'sehr wenige Steckdosen, Schalter und Sicherungen, kein Fehlerstromschutzschalter (FI-Schalter), Leitungen teilweise auf Putz', 9, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(82, 2, 'wenige Steckdosen, Schalter und Sicherungen', 9, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(83, 3, 'zeitgemäße Anzahl an Steckdosen und Lichtauslässen, Zählerschrank (ab ca. 1985) mit Unterverteilung und Kippsicherungen', 9, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(84, 4, 'zahlreiche Steckdosen und Lichtaus lässe, hochwertige Abdeckungen, dezentrale Lüftung mit Wärmetauscher, mehrere LAN- und Fernsehanschlüsse', 9, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(85, 5, 'Video- und zentrale Alarmanlage, zentrale Lüftung mit Wärmetauscher, Klimaanlage, Bussystem', 9, 1);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(86, 3, 'ein-/zweischaliges Mauerwerk, z. B. aus Leichtziegeln, Kalksandsteinen, Gasbetonsteinen', 1, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(87, 3, 'Edelputz', 1, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(88, 3, 'Wärmedämmverbundsystem oder Wärmedämmputz (nach ca. 1995)', 1, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(89, 4, 'Verblendmauerwerk, zweischalig, hinterlüftet, Vorhangfassade (z. B. Naturschiefer)', 1, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(90, 4, 'Wärmedämmung (nach ca. 2005)', 1, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(91, 5, 'aufwendig gestaltete Fassaden mit konstruktiver Gliederung (Säulenstellungen, Erker etc.), Sichtbeton-Fertigteile, Natursteinfassade, Elemente aus Kupfer-/Eloxalblech, mehrgeschossige Glasfassaden;', 1, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(92, 5, 'hochwertigste Dämmung', 1, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(93, 3, 'Faserzement-Schindeln, beschichtete Betondachsteine und Tondachziegel, Folienabdichtung', 2, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(94, 3, 'Dachdämmung (nach ca. 1995)', 2, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(95, 4, 'glasierte Tondachziegel', 2, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(96, 4, 'Flachdachausbildung tlw. als Dachterrasse', 2, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(97, 4, 'Konstruktion in Brettschichtholz, schweres Massivflachdach', 2, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(98, 4, 'besondere Dachform, z. B. Mansarden-, Walmdach', 2, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(99, 4, 'Aufsparrendämmung, überdurchschnittliche Dämmung (nach ca. 2005)', 2, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(100, 5, 'hochwertige Eindeckung z. B. aus Schiefer oder Kupfer, Dachbegrünung, befahrbares Flachdach', 2, 2); ",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(101, 5, 'stark überdurchschnittliche Dämmung', 2, 2); ",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(102, 3, 'Zweifachverglasung (nach ca. 1995), Rollläden (manuell)', 3, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(103, 3, 'Haustür mit zeitgemäßem Wärmeschutz (nach ca. 1995)', 3, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(104, 4, 'Dreifachverglasung, Sonnenschutzglas, aufwendigere Rahmen, Rollläden (elektr.)', 3, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(105, 4, 'höherwertige Türanlagen z. B. mit Seitenteil, besonderer Einbruchschutz', 3, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(106, 5, 'große feststehende Fensterflächen, Spezialverglasung (Schall- und Sonnenschutz)', 3, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(107, 5, 'Außentüren in hochwertigen Materialien', 3, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(108, 3, 'nicht tragende Innenwände in massiver Ausführung bzw. mit Dämmmaterial gefüllte Ständerkonstruktionen', 4, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(109, 3, 'schwere Türen', 4, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(110, 4, 'Sichtmauerwerk', 4, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(111, 4, 'Massivholztüren, Schiebetürelemente, Glastüren, strukturierte Türblätter', 4, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(112, 5, 'gestaltete Wandabläufe (z.B. Pfeilervorlagen, abgesetzte oder geschwungene Wandpartien)', 4, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(113, 5, 'Brandschutzverkleidung; raumhohe aufwendige Türelemente', 4, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(114, 3, 'Betondecken mit Tritt- und Luftschallschutz (z. B. schwimmender Estrich)', 5, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(115, 3, 'einfacher Putz', 5, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(116, 4, 'zusätzlich Deckenverkleidung', 5, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(117, 5, 'Deckenvertäfelungen (Edelholz, Metall)', 5, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(118, 3, 'Linoleum-, Teppich-, Laminat- und PVC-Böden besserer Art und Ausführung, Fliesen, Kunststeinplatten', 6, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(119, 4, 'Natursteinplatten, Fertigparkett, hochwertige Fliesen, Terrazzobelag, hochwertige Massivholzböden auf gedämmter Unterkonstruktion', 6, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(120, 5, 'hochwertiges Parkett, hochwertige Natursteinplatten, hochwertige Edelholzböden auf gedämmter Unterkonstruktion', 6, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(121, 3, '1 Bad mit WC je Wohneinheit', 7, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(122, 3, 'Dusche und Badewanne', 7, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(123, 3, 'Wand- und Bodenfliesen, raumhoch gefliest', 7, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(124, 4, '1 bis 2 Bäder je Wohneinheit mit tlw. zwei Waschbecken, tlw. Bidet/Urinal, Gäste-WC, bodengleiche Dusche', 7, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(125, 4, 'Wand- und Bodenfliesen jeweils in gehobener Qualität', 7, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(126, 5, '2 und mehr Bäder je Wohneinheit', 7, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(127, 5, 'hochwertige Wand- und Bodenplatten (oberflächenstrukturiert, Einzel- und Flächendekors)', 7, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(128, 3, 'elektronisch gesteuerte Fern- oder Zentralheizung, Niedertemperatur- oder Brennwertkessel', 8, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(129, 4, 'Fußbodenheizung, Solarkollektoren für Warmwassererzeugung', 8, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(130, 5, 'Solarkollektoren für Warmwassererzeugung und Heizung, Blockheizkraftwerk, Wärmepumpe, Hybrid-Systeme', 8, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(131, 3, 'zeitgemäße Anzahl an Steckdosen und Lichtauslässen', 9, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(132, 3, 'Zählerschrank (ab ca. 1985) mit Unterverteilung und Kippsicherungen', 9, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(133, 4, 'zahlreiche Steckdosen und Lichtauslässe, hochwertige Abdeckungen, dezentrale Lüftung mit Wärmetauscher, mehrere LAN- und Fernsehanschlüsse, Personenaufzugsanlagen', 9, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(134, 5, 'Video- und zentrale Alarmanlage, zentrale Lüftung mit Wärmetauscher, Klimaanlage', 9, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(135, 5, 'Bussystem', 9, 2);",
                @"INSERT INTO `StandardLevelProperty` (ID, Stufe, Beschreibung, GebTeilId, StdTabellenId) VALUES(136, 5, 'aufwendige Personenaufzugsanlagen', 9, 2);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 1, 1, 655.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 1, 2, 725.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 1, 3, 835.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 1, 4, 1005.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 1, 5, 1260.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 2, 1, 615.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 2, 2, 685.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 2, 3, 785.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 2, 4, 945.0);",
                @" INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 2, 5, 1180.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 3, 1, 575.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 3, 2, 640.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 3, 3, 735.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 3, 4, 885.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 1, 3, 5, 1105.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 1, 1, 545.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 1, 2, 605.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 1, 3, 695.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 1, 4, 840.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 1, 5, 1050.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 2, 1, 515.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 2, 2, 570.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 2, 3, 655.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 2, 4, 790.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 2, 5, 985.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 3, 1, 480.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 3, 2, 535.0);",
                @"INSERT INTO `NHKosten` (BauweiseId, AusbZustandId, GebArtId, Standardstufe, KostenProM2) VALUES(1, 2, 3, 3, 615.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,2,3,4,740.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,2,3,5,925.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,1,1,705.0); ",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,1,2,785.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,1,3,900.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,1,4,1085.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,1,5,1360.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,2,1,665.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,2,2,735.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,2,3,845.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,2,4,1020.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,2,5,1275.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,3,1,620.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,3,2,690.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,3,3,795.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,3,4,955.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (1,3,3,5,1195.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,1,1,655.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,1,2,725.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,1,3,835.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,1,4,1005.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,1,5,1260.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,2,1,615.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,2,2,685.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,2,3,785.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,2,4,945.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,2,5,1180.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,3,1,575.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,3,2,640.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,3,3,735.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,3,4,885.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,1,3,5,1105.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,1,1,570.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,1,2,635.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,1,3,730.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,1,4,880.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,1,5,1100.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,2,1,535.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,2,2,595.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,2,3,685.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,2,4,825.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,2,5,1035.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,3,1,505.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,3,2,560.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,3,3,640.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,3,4,775.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,2,3,5,965.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,1,1,665.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,1,2,740.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,1,3,850.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,1,4,1025.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,1,5,1285.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,2,1,625.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,2,2,695.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,2,3,800.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,2,4,965.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,2,5,1205.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,3,1,585.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,3,2,650.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,3,3,750.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,3,4,905.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (2,3,3,5,1130.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,1,1,790.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,1,2,875.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,1,3,1005.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,1,4,1215.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,1,5,1515.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,2,1,740.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,2,2,825.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,2,3,945.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,2,4,1140.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,2,5,1425.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,3,1,695.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,3,2,770.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,3,3,885.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,3,4,1065.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,1,3,5,1335.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,1,1,585.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,1,2,650.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,1,3,745.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,1,4,900.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,1,5,1125.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,2,1,550.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,2,2,610.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,2,3,700.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,2,4,845.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,2,5,1055.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,3,1,515.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,3,2,570.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,3,3,655.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,3,4,790.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,2,3,5,990.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,1,1,920.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,1,2,1025.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,1,3,1180.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,1,4,1420.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,1,5,1775.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,2,1,865.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,2,2,965.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,2,3,1105.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,2,4,1335.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,2,5,1670.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,3,1,810.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,3,2,900.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,3,3,1035.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,3,4,1250.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (3,3,3,5,1560.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,1,1,720.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,1,2,800.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,1,3,920.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,1,4,1105.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,1,5,1385.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,2,1,675.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,2,2,750.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,2,3,865.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,2,4,1040.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,2,5,1300.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,3,1,635.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,3,2,705.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,3,3,810.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,3,4,975.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,1,3,5,1215.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,1,1,620.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,1,2,690.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,1,3,790.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,1,4,955.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,1,5,1190.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,2,1,580.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,2,2,645.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,2,3,745.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,2,4,895.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,2,5,1120.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,3,1,545.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,3,2,605.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,3,3,695.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,3,4,840.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,2,3,5,1050.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,1,1,785.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,1,2,870.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,1,3,1000.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,1,4,1205.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,1,5,1510.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,2,1,735.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,2,2,820.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,2,3,940.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,2,4,1135.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,2,5,1415.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,3,1,690.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,3,2,765.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,3,3,880.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,3,4,1060.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (4,3,3,5,1325.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (5,NULL,4,3,825.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (5,NULL,4,4,985.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (5,NULL,4,5,1190.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (6,NULL,4,3,765.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (6,NULL,4,4,915.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (6,NULL,4,5,1105.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (7,NULL,4,3,755.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (7,NULL,4,4,900.0);",
                @"INSERT INTO `NHKosten` (BauweiseId,AusbZustandId,GebArtId,Standardstufe,KostenProM2) VALUES (7,NULL,4,5,1090.0);",
                @"INSERT INTO `Modernisierungsgrad` (Punkte,Grad,Koeffa,Koeffb,Koeffc,AbRelAlter) VALUES (1,'nicht modernisiert',0.0125,2.625,152.5,60);",
                @"INSERT INTO `Modernisierungsgrad` (Punkte,Grad,Koeffa,Koeffb,Koeffc,AbRelAlter) VALUES (4,'kleine Modernisierungen im Rahmen der Instandhaltung',0.0073,1.577,111.33,40);",
                @"INSERT INTO `Modernisierungsgrad` (Punkte,Grad,Koeffa,Koeffb,Koeffc,AbRelAlter) VALUES (8,'mittlerer Modernisierungsgrad',0.005,1.1,100.0,20);",
                @"INSERT INTO `Modernisierungsgrad` (Punkte,Grad,Koeffa,Koeffb,Koeffc,AbRelAlter) VALUES (13,'überwiegend modernisiert',0.0033,0.735,95.28,15);",
                @"INSERT INTO `Modernisierungsgrad` (Punkte,Grad,Koeffa,Koeffb,Koeffc,AbRelAlter) VALUES (18,'umfassend modernisiert',0.002,0.44,94.2,10);",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (1,4,'Dacherneuerung inklusive Verbesserung der Wärmedämmung');",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (2,2,'Modernisierung der Fenster und Außentüren');",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (3,2,'Modernisierung der Leitungssysteme (Strom, Gas, Wasser, Abwasser)');",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (4,2,'Modernisierung der Heizungsanlage');",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (5,4,'Wärmedämmung der Außenwände');",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (6,2,'Modernisierung von Bädern');",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (7,2,'Modernisierung des Innenausbaus, z.B. Decken Fußböden, Treppen');",
                @"INSERT INTO `Modernisierung` (ID,MaxPunkte,ModernElement) VALUES (8,2,'Wesentliche Verbesserung der Grundrissgestaltung');",
                @"INSERT INTO `Korrekturfaktortyp` (Id,Bezeichnung,Interpolierbar) VALUES (1,'Gebäudetyp',0);",
                @"INSERT INTO `Korrekturfaktortyp` (Id,Bezeichnung,Interpolierbar) VALUES (2,'Wohnungsgröße pro Wohneinheit',1);",
                @"INSERT INTO `Korrekturfaktortyp` (Id,Bezeichnung,Interpolierbar) VALUES (3,'Grundrissart',0);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (1,1,'freistehendes Zweifamilienhaus',1.05,NULL);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (1,1,'freistehendes Einfamilienhaus',1.0,NULL);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (4,2,'Ca. 35 m2 WF/WE',1.1,35.0);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (4,2,'Ca. 50 m2 WF/WE',1.0,50.0);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (4,2,'Ca. 135 m2 WF/WE',0.85,135.0);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (4,3,'Einspänner',1.05,NULL);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (4,3,'Zweispänner',1.0,NULL);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (4,3,'Dreispänner',0.97,NULL);",
                @"INSERT INTO `Korrekturfaktor` (GebArtId,TypId,Beschreibung,Faktor,XVal) VALUES (4,3,'Vierspänner',0.95,NULL);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (1,'1',60);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (1,'2',65);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (1,'3',70);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (1,'4',75);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (1,'5',80);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (2,'1',60);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (2,'2',65);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (2,'3',70);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (2,'4',75);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (2,'5',80);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (3,'1',60);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (3,'2',65);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (3,'3',70);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (3,'4',75);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (3,'5',80);",
                @"INSERT INTO `Gesamtnutzungsdauer` (GebArtId,StdStufe,Dauer) VALUES (4,NULL,70);",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (1,'Außenwände');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (2,'Dach');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (3,'Fenster und Außentüren');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (4,'Innenwände und -türen');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (5,'Deckenkonstruktion und Treppen');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (6,'Fußböden');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (7,'Sanitäreinrichtungen');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (8,'Heizung');",
                @"INSERT INTO `Gebaeudeteil` (ID,Bezeichnung) VALUES (9,'Sonstige technische Ausstattung');",
                @"INSERT INTO `Gebaeudeart` (ID,Bezeichnung,StandardTableId) VALUES (1,'Freistehendes Ein- und Zweifamilienhaus',1);",
                @"INSERT INTO `Gebaeudeart` (ID,Bezeichnung,StandardTableId) VALUES (2,'Doppel- und Reihenendhaus',1);",
                @"INSERT INTO `Gebaeudeart` (ID,Bezeichnung,StandardTableId) VALUES (3,'Reihenmittelhaus',1);",
                @"INSERT INTO `Gebaeudeart` (ID,Bezeichnung,StandardTableId) VALUES (4,'Mehrfamilienhaus',2);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,1,23);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,2,15);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,3,11);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,4,11);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,5,11);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,6,5);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,7,9);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,8,9);",
                @"INSERT INTO `GebTeilWaegung` (StdTabellenId,GebTeilId,Waegung) VALUES (1,9,6);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (1,1);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (1,2);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (1,3);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (1,4);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (2,1);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (2,2);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (2,3);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (2,4);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (3,1);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (3,2);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (3,3);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (3,4);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (4,5);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (4,6);",
                @"INSERT INTO `GebArtXBauweise` (GebArtId,BauweiseId) VALUES (4,7);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (1,1);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (1,2);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (1,3);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (2,1);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (2,2);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (2,3);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (3,1);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (3,2);",
                @"INSERT INTO `GebArtXAusbau` (GebArtId,ZustandId) VALUES (3,3);",
                @"INSERT INTO `GebArtBaupreisindex` (GebArtId,StdTabellenId) VALUES (1,1);",
                @"INSERT INTO `GebArtBaupreisindex` (GebArtId,StdTabellenId) VALUES (2,1);",
                @"INSERT INTO `GebArtBaupreisindex` (GebArtId,StdTabellenId) VALUES (3,1);",
                @"INSERT INTO `GebArtBaupreisindex` (GebArtId,StdTabellenId) VALUES (4,1);",
                @"INSERT INTO `Bauweise` (ID,Bezeichnung) VALUES (1,'Keller-, Erdgeschoss');",
                @"INSERT INTO `Bauweise` (ID,Bezeichnung) VALUES (2,'Keller-, Erd-, Obergeschoss');",
                @"INSERT INTO `Bauweise` (ID,Bezeichnung) VALUES (3,'Erdgeschoss, nicht unterkellert');",
                @"INSERT INTO `Bauweise` (ID,Bezeichnung) VALUES (4,'Erd-, Obergeschoss, nicht unterkellert');",
                @"INSERT INTO `Bauweise` (ID,Bezeichnung) VALUES (5,'mit bis zu 6 WE');",
                @"INSERT INTO `Bauweise` (ID,Bezeichnung) VALUES (6,'mit 7 bis 20 WE');",
                @"INSERT INTO `Bauweise` (ID,Bezeichnung) VALUES (7,'mit mehr als 20 WE');",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2010,1,99.2,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2010,2,99.9,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2010,3,100.3,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2010,4,100.6,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2011,1,101.8,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2011,2,102.5,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2011,3,103.2,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2011,4,103.5,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2012,1,104.6,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2012,2,105.2,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2012,3,105.7,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2012,4,106.0,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2013,1,106.8,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2013,2,107.4,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2013,3,107.8,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2013,4,108.1,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2014,1,108.9,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2014,2,109.2,0);",
                @"INSERT INTO `Baupreisindex` (StdTabellenId,Jahr,Quartal,[Index],Aenderbar) VALUES (1,2014,3,109.6,0);",
                @"INSERT INTO `Ausbauzustand` (ID,Bezeichnung) VALUES (1,'Dachgeschoss voll ausgebaut');",
                @"INSERT INTO `Ausbauzustand` (ID,Bezeichnung) VALUES (2,'Dachgeschoss nicht ausgebaut');",
                @"INSERT INTO `Ausbauzustand` (ID,Bezeichnung) VALUES (3,'Flachdach oder flachgeneigtes Dach');"
            };
            return builder2;
        }
        private void CheckDbAndSeed(string dbPath)
        {
            if (!CheckDbExistence(dbPath))
            {
                using (var db = new SQLite.SQLiteConnection(dbPath))
                {
                    db.CreateTable<GebaeudeartEntity>();
                    db.CreateTable<ImmobilieEntity>();
                    db.CreateTable<GebBauweiseEntity>();
                    db.CreateTable<GebAusbauzustandEntity>();
                    db.CreateTable<GebArtXBauweiseEntity>();
                    db.CreateTable<GebArtXAusbauEntity>();
                    db.CreateTable<GebArtBaupreisindexEntity>();
                    db.CreateTable<BaupreisindexEntity>();
                    db.CreateTable<ModernisierungEntity>();
                    db.CreateTable<ModernisierungsgradEntity>();
                    db.CreateTable<NHKostenEntity>();
                    db.CreateTable<StandardLevelPropertyEntity>();
                    db.CreateTable<EstateStandardLevelPropertyEntity>();
                    db.CreateTable<GebaeudeteilEntity>();
                    db.CreateTable<WaegungsanteilEntity>();
                    db.CreateTable<ImmobilieBildEntity>();
                    db.CreateTable<PartStandardEntity>();
                    db.CreateTable<ImmobilieModernisierungEntity>();
                    db.CreateTable<GesamtnutzungsdauerEntity>();
                    db.CreateTable<KorrekturfaktorEntity>();
                    db.CreateTable<KorrekturfaktortypEntity>();
                    db.CreateTable<ImmobilieKorrFaktorEntity>();
                    List<string> seedStringList = GetSeedStringFromList();
                    foreach (var item in seedStringList)
                    {
                        db.Execute(item);
                    }
                }
            }
        }
        private bool CheckDbExistence(string dbPath)
        {
            bool dbExists = true;
            try
            {
                using (var db = new SQLite.SQLiteConnection(dbPath, SQLite.SQLiteOpenFlags.ReadWrite))
                {
                }
            }
            catch (SQLite.SQLiteException)
            {
                dbExists = false;
            }
            return dbExists;
        }
        #endregion
    }
}
